import {
  CreditCard,
  Droplets,
  ClipboardList,
  Building,
  Ruler,
  BusFront,
  Construction,
  UserMinus,
  MapPin,
  Leaf,
  MessageSquare,
  Map,
  Building2,
  Navigation,
  GraduationCap,
  Handshake,
  AlertTriangle,
  Ticket,
  Clock,
  Megaphone,
  Theater,
  Newspaper,
  Briefcase,
  BarChart3,
  TrendingUp,
  Target,
  Banknote,
  Recycle,
  Bus,
  ParkingCircle,
  FileText,
  Scale,
  Hospital,
  Download,
  FileEdit,
  Tv,
  Users,
  Dog,
} from "lucide-react";

export const TAB_DATA = {
  hizmetTabs: [
    {
      id: "belediye",
      label: "Belediye Hizmetleri",
      items: [
        { id: "1", label: "Hızlı Borç Ödeme", Icon: CreditCard },
        { id: "2", label: "Su Faturası Ödeme", Icon: Droplets },
        { id: "3", label: "İhale Doğrudan Temin", Icon: ClipboardList },
        { id: "4", label: "İmar Değişiklikleri", Icon: Building },
        { id: "5", label: "18. Madde İmar Uyg.", Icon: Ruler },
        { id: "6", label: "UKOME Kararları", Icon: BusFront },
        { id: "7", label: "AYKOME Yönetmelik", Icon: Construction },
        { id: "8", label: "Vefat Edenler", Icon: UserMinus },
        { id: "9", label: "E-Mezarlık Sistemi", Icon: MapPin },
        { id: "10", label: "Hal Fiyatları", Icon: Leaf },
        { id: "11", label: "İstek Şikayet", Icon: MessageSquare },
        { id: "12", label: "Kent Rehberi", Icon: Map },
        { id: "13", label: "Ulusal Kent Rehberi", Icon: Building2 },
        { id: "14", label: "TBB Yol Haritası", Icon: Navigation },
        { id: "15", label: "TEMEK Meslek Kursları", Icon: GraduationCap },
        { id: "16", label: "Sosyal Yardım Portalı", Icon: Handshake },
        { id: "17", label: "Afet Toplanma Alanları", Icon: AlertTriangle },
        { id: "18", label: "Tekirdağ Kart Bakiye", Icon: Ticket },
        { id: "19", label: "Otobüs Sefer Saatleri", Icon: Clock },
        { id: "20", label: "Personel A.Ş. İlanları", Icon: Megaphone },
        { id: "21", label: "Şehir Tiyatroları", Icon: Theater },
      ],
    },
    {
      id: "yayinlar",
      label: "Yayınlar",
      items: [
        { id: "y1", label: "E-Bülten Arşivi", Icon: Newspaper },
        { id: "y2", label: "Kurumsal Kimlik", Icon: Briefcase },
        { id: "y3", label: "Faaliyet Raporları", Icon: BarChart3 },
        { id: "y4", label: "Performans Programları", Icon: TrendingUp },
        { id: "y5", label: "Stratejik Plan", Icon: Target },
        { id: "y6", label: "Gelir Tarifeleri", Icon: Banknote },
        { id: "y7", label: "Katı Atık Yönetimi", Icon: Recycle },
        { id: "y8", label: "Toplu Taşıma Ücretleri", Icon: Bus },
        { id: "y9", label: "Harcırah Ücretleri", Icon: BusFront },
        { id: "y10", label: "Otopark Yönetmeliği", Icon: ParkingCircle },
        { id: "y11", label: "Kamu Hizmet Standartları", Icon: FileText },
        { id: "y12", label: "Mali Beklentiler", Icon: FileText },
        { id: "y13", label: "Mevzuat", Icon: Scale },
        { id: "y14", label: "İç Kontrol Eylem Planı", Icon: FileText },
        { id: "y15", label: "Tıbbi Atık Yönetim", Icon: Hospital },
        { id: "y16", label: "Kurumsal Logo İndir", Icon: Download },
      ],
    },
    {
      id: "basvurular",
      label: "Başvurular ve Diğer Siteler",
      items: [
        { id: "b1", label: "Başvuru Formları", Icon: FileEdit },
        { id: "b2", label: "Büyükşehir TV", Icon: Tv },
        { id: "b3", label: "Personel A.Ş. Sitesi", Icon: Users },
        { id: "b4", label: "TEKULAŞ Sitesi", Icon: Bus },
        { id: "b5", label: "TESKİ Sitesi", Icon: Droplets },
        { id: "b6", label: "Meslek Kursları Başvuru", Icon: GraduationCap },
        { id: "b7", label: "Sosyal Portal", Icon: Handshake },
        { id: "b8", label: "Tekirdağ Afete Hazır", Icon: AlertTriangle },
        { id: "b9", label: "Şehir Tiyatroları", Icon: Theater },
        { id: "b10", label: "Sahipsiz Hayvan Bakımevi", Icon: Dog },
      ],
    },
  ],
  duyuruTabs: [
    {
      id: "guncel",
      label: "Güncel Duyurular",
      items: [
        { id: "d1", title: "2026 Yaz Dönemi Sosyal Projeler Başvuruları", date: "01/07/2026" },
        { id: "d2", title: "Şehir Tiyatroları Yeni Sezon Bilet Satışları", date: "28/06/2026" },
      ],
    },
    {
      id: "ihale",
      label: "İhale / Doğrudan Temin",
      items: [
        { id: "i1", title: "Asfalt Yenileme İhalesi", date: "30/06/2026" },
        { id: "i2", title: "Park Bahçe Malzeme Alımı", date: "29/06/2026" },
      ],
    },
  ],
};