import {
  CreditCard,
  Droplets,
  ClipboardList,
  Building,
  Ruler,
  BusFront,
  Construction,
  UserMinus,
  MapPin,
  Leaf,
  MessageSquare,
  Map,
  Building2,
  Navigation,
  GraduationCap,
  Handshake,
  AlertTriangle,
  Ticket,
  Clock,
  Megaphone,
  Theater,
  Newspaper,
  Briefcase,
  BarChart3,
  TrendingUp,
  Target,
  Banknote,
  Recycle,
  Bus,
  ParkingCircle,
  FileText,
  Scale,
  Hospital,
  Download,
  FileEdit,
  Tv,
  Users,
  Dog,
} from "lucide-react";

export const TAB_DATA = {
  hizmetTabs: [
    {
      id: "belediye",
      label: "Belediye Hizmetleri",
      items: [
        { id: "1", label: "Hızlı Borç Ödeme", Icon: CreditCard, href: "https://ebelediye.tekirdag.bel.tr" },
        { id: "2", label: "Su Faturası Ödeme", Icon: Droplets, href: "https://www.teski.gov.tr/sube/index.aspx" },
        { id: "3", label: "İhale Doğrudan Temin", Icon: ClipboardList, href: "/hizmetler/ihale-duyuru" },
        { id: "4", label: "İmar Değişiklikleri", Icon: Building, href: "/hizmetler/imar-degisiklikleri" },
        { id: "5", label: "18. Madde İmar Uyg.", Icon: Ruler, href: "/hizmetler/18-madde-imar-uygulamasi" },
        { id: "6", label: "UKOME Kararları", Icon: BusFront, href: "/hizmetler/ukome" },
        { id: "7", label: "AYKOME Yönetmelik", Icon: Construction, href: "/hizmetler/aykome" },
        { id: "8", label: "Vefat Edenler", Icon: UserMinus, href: "/merhumlar" },
        { id: "9", label: "E-Mezarlık Sistemi", Icon: MapPin, href: "https://emezarlik.tekirdag.bel.tr/" },
        { id: "10", label: "Hal Fiyatları", Icon: Leaf, href: "/hizmetler/hal-fiyatlari" },
        { id: "11", label: "İstek Şikayet", Icon: MessageSquare, href: "/istek-sikayet" },
        { id: "12", label: "Kent Rehberi", Icon: Map, href: "https://harita.tekirdag.bel.tr/kentrehberi/" },
        { id: "13", label: "Ulusal Kent Rehberi", Icon: Building2, href: "#" },
        { id: "14", label: "TBB Yol Haritası", Icon: Navigation, href: "#" },
        { id: "15", label: "TEMEK Meslek Kursları", Icon: GraduationCap, href: "#" },
        { id: "16", label: "Sosyal Yardım Portalı", Icon: Handshake, href: "#" },
        { id: "17", label: "Afet Toplanma Alanları", Icon: AlertTriangle, href: "#" },
        { id: "18", label: "Tekirdağ Kart Bakiye", Icon: Ticket, href: "#" },
        { id: "19", label: "Otobüs Sefer Saatleri", Icon: Clock, href: "#" },
        { id: "20", label: "Personel A.Ş. İlanları", Icon: Megaphone, href: "#" },
        { id: "21", label: "Şehir Tiyatroları", Icon: Theater, href: "#" },
      ],
    },
    {
      id: "yayinlar",
      label: "Yayınlar",
      items: [
        { id: "y1", label: "E-Bülten Arşivi", Icon: Newspaper, href: "/yayinlar/e-bulten" },
        { id: "y2", label: "Kurumsal Kimlik", Icon: Briefcase, href: "#" },
        { id: "y3", label: "Faaliyet Raporları", Icon: BarChart3, href: "/yayinlar/faaliyet-raporlari" },
        { id: "y4", label: "Performans Programları", Icon: TrendingUp, href: "#" },
        { id: "y5", label: "Stratejik Plan", Icon: Target, href: "#" },
        { id: "y6", label: "Gelir Tarifeleri", Icon: Banknote, href: "#" },
        { id: "y7", label: "Katı Atık Yönetimi", Icon: Recycle, href: "#" },
        { id: "y8", label: "Toplu Taşıma Ücretleri", Icon: Bus, href: "#" },
        { id: "y9", label: "Harcırah Ücretleri", Icon: BusFront, href: "#" },
        { id: "y10", label: "Otopark Yönetmeliği", Icon: ParkingCircle, href: "#" },
        { id: "y11", label: "Kamu Hizmet Standartları", Icon: FileText, href: "#" },
        { id: "y12", label: "Mali Beklentiler", Icon: FileText, href: "#" },
        { id: "y13", label: "Mevzuat", Icon: Scale, href: "#" },
        { id: "y14", label: "İç Kontrol Eylem Planı", Icon: FileText, href: "#" },
        { id: "y15", label: "Tıbbi Atık Yönetim", Icon: Hospital, href: "#" },
        { id: "y16", label: "Kurumsal Logo İndir", Icon: Download, href: "#" },
      ],
    },
    {
      id: "basvurular",
      label: "Başvurular ve Diğer Siteler",
      items: [
        { id: "b1", label: "Başvuru Formları", Icon: FileEdit, href: "#e-islemler" },
        { id: "b2", label: "Büyükşehir TV", Icon: Tv, href: "#" },
        { id: "b3", label: "Personel A.Ş. Sitesi", Icon: Users, href: "#" },
        { id: "b4", label: "TEKULAŞ Sitesi", Icon: Bus, href: "#" },
        { id: "b5", label: "TESKİ Sitesi", Icon: Droplets, href: "https://www.teski.gov.tr" },
        { id: "b6", label: "Meslek Kursları Başvuru", Icon: GraduationCap, href: "#" },
        { id: "b7", label: "Sosyal Portal", Icon: Handshake, href: "#" },
        { id: "b8", label: "Tekirdağ Afete Hazır", Icon: AlertTriangle, href: "#" },
        { id: "b9", label: "Şehir Tiyatroları", Icon: Theater, href: "#" },
        { id: "b10", label: "Sahipsiz Hayvan Bakımevi", Icon: Dog, href: "#" },
      ],
    },
  ],
  duyuruTabs: [
    {
      id: "guncel",
      label: "Güncel Duyurular",
      items: [
        { id: "d1", title: "2026 Yaz Dönemi Sosyal Projeler Başvuruları", date: "01/07/2026", href: "#" },
        { id: "d2", title: "Şehir Tiyatroları Yeni Sezon Bilet Satışları", date: "28/06/2026", href: "#" },
      ],
    },
    {
      id: "ihale",
      label: "İhale / Doğrudan Temin",
      items: [
        { id: "i1", title: "Asfalt Yenileme İhalesi", date: "30/06/2026", href: "/hizmetler/ihale-duyuru" },
        { id: "i2", title: "Park Bahçe Malzeme Alımı", date: "29/06/2026", href: "/hizmetler/ihale-duyuru" },
      ],
    },
  ],
};